#!/usr/bin/env bash
sudo -v

cd "$(dirname "${BASH_SOURCE}")"

git pull origin master

# copy files
rsync --exclude ".git/" --exclude ".DS_Store" --exclude "bootstrap" --exclude ".extra" \
    --exclude "README" --exclude "LICENSE" --exclude ".sublime-settings" -av --no-perms . ~

# sync OS X settings
~/.osx

# Sublime settings and binaries
ln -Ffs ~/.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 2/Packages/User/Preferences.sublime-settings
ln -s /Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl > /dev/null 2>&1

# update git configurations
git config --global core.excludesfile '~/.gitignore_global'

source ~/.profile
