#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SRC_DIR="${SCRIPT_DIR}/src"
cd $SRC_DIR

echo "Linking files"
for SRC_FILE in $(find . -type f ! -name '.gitkeep' | sed "s|^\./||" | sort); do
        DST_FILE=$HOME/$SRC_FILE
        DST_DIR=$(dirname $DST_FILE)

        mkdir -p $DST_DIR
        if ! ln -sfr $SRC_FILE $DST_FILE 2> /dev/null ; then  # no relative link support (OS X)
          SRC_FILE_ABS="${SRC_DIR}/${SRC_FILE}"
          ln -sf $SRC_FILE_ABS $DST_FILE
        fi
        echo "$SRC_FILE -> $DST_FILE"
done

echo ""
echo "Installing Tmux Plugin Manager"
TMUX_PLUGIN_DIR="${HOME}/.tmux/plugins/tpm"
if [ -d $TMUX_PLUGIN_DIR ]; then
  echo "... already installed. skipping clone"
else
  git clone https://github.com/tmux-plugins/tpm $TMUX_PLUGIN_DIR
fi

echo ""
echo "Installing Vundle"
VUNDLE_DIR="${HOME}/.vim/bundle/Vundle.vim"
if [ -d $VUNDLE_DIR ]; then
  echo "... already installed. skipping clone"
else
  git clone https://github.com/VundleVim/Vundle.vim.git $VUNDLE_DIR
fi

echo ""
echo "Installing Vim Plugins"
vim +PluginInstall +qall
