#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SRC_DIR="${SCRIPT_DIR}/src"
cd $SRC_DIR

echo "Linking files"
for SRC_FILE in $(find . -type f ! -name '.gitkeep' | sed "s|^\./||" | sort); do
        DST_FILE=$HOME/$SRC_FILE
        DST_DIR=$(dirname $DST_FILE)

        mkdir -p $DST_DIR
        if ! ln -sfr $SRC_FILE $DST_FILE 2> /dev/null ; then  # no relative link support (OS X)
          SRC_FILE_ABS="${SRC_DIR}/${SRC_FILE}"
          ln -sf $SRC_FILE_ABS $DST_FILE
        fi
        echo "$SRC_FILE -> $DST_FILE"
done

echo ""
echo "Installing Packer"
PACKER_DIR="${HOME}/.local/share/nvim/site/pack/packer/start/packer.nvim"
if [ -d $PACKER_DIR ]; then
  echo "... already installed. skipping clone"
else
  git clone --depth 1 https://github.com/wbthomason/packer.nvim $PACKER_DIR
fi

echo ""
echo "Installing Kitty term colours"
KITTY_BASE16_DIR="${HOME}/.local/share/kitty/base16-kitty"
if [ -d $KITTY_BASE16_DIR ]; then
  echo "... already installed. skipping clone"
else
  git clone https://github.com/kdrag0n/base16-kitty.git $KITTY_BASE16_DIR
fi
