#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $SCRIPT_DIR/src

echo "Linking files"
for SRC_FILE in $(find -type f ! -name '.gitkeep' -printf '%P\n' | sort); do
	DST_FILE=$HOME/$SRC_FILE
	DST_DIR=$(dirname $DST_FILE)

	mkdir -p $DST_DIR
	ln -sfr $SRC_FILE $DST_FILE
	echo "$SRC_FILE -> $DST_FILE"
done
echo ""

echo "Cloning Vundle"
git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
